modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory
credits="Thanks for this example mod goes to Java" #optional
authors="Sauuuuucey" #optional

[[mods]] #mandatory
modId="sauuuuuceysfarming" #mandatory
version="1.0-beta" #mandatory
displayName="Sauuuuucey's Farming" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
Sauuuuucey's Farming adds new crops and foods to the game, in a realistic-esque fashion, to farming more of a variety in what you can grow. 
"Did you do it?" "Yes." "What did it cost?" "Bonemeal."
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[27,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"